#!/bin/bash

#Compiz rotate plugin's "initiate" button
xdotool mousedown 9

#Pixels to move mouse (rotates cube)
step=1

#Start rotation left or right at random
direction=$RANDOM; let "direction >>= 14"
[[ "$direction" -eq 1 ]] && direction=90 || direction=270

#Cube rotation screensaver
while [ $(xprintidle) -gt 0 ]; do
  xdotool mousemove_relative --polar "$direction" "$step"
  #Approximately 60fps
  sleep 0.0165
done

#Compiz rotate plugin's "initiate" button
xdotool mouseup 9
